// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
//
// Bu dosya `dart run flutterfire configure` ile güncellenir — elle düzenlemeyin.
// Yerel çıktı: android/app/google-services.json, ios/Runner/GoogleService-Info.plist

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// `Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform)`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web için firebase_options tanımlı değil; FlutterFire ile web seçerek yeniden çalıştırın.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'Bu platform için FirebaseOptions yapılandırılmadı.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0LIgx7miepp0bOYWYMoqIW9S9yGC904o',
    appId: '1:736252281874:android:7c22dd7386e3154c0444cb',
    messagingSenderId: '736252281874',
    projectId: 'taksim-gelsin-433f0',
    storageBucket: 'taksim-gelsin-433f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnghX-K8-UniatfZEhgvyvM4uN1U-0Ky8',
    appId: '1:736252281874:ios:ae6bbc1d8c7f00410444cb',
    messagingSenderId: '736252281874',
    projectId: 'taksim-gelsin-433f0',
    storageBucket: 'taksim-gelsin-433f0.firebasestorage.app',
    iosBundleId: 'com.taksimgelsin.taksiapp',
  );

}